package com.example.bvtv_www.service;

import com.example.bvtv_www.entity.Order;
import com.example.bvtv_www.entity.Profile;
import com.example.bvtv_www.repository.OrderRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import java.util.List;
import jakarta.persistence.EntityManager;
import org.springframework.transaction.annotation.Transactional;

@Service
@RequiredArgsConstructor
public class OrderService {
    private final OrderRepository orderRepository;
    private final ProfileService profileService;
    private final EntityManager entityManager;

    public List<Order> findAll() {
        return orderRepository.findAll();
    }

    public Order findById(Long id) {
        return orderRepository.findById(id)
            .orElseThrow(() -> new RuntimeException("Order not found"));
    }

    public Order findByOrderNo(String orderNo) {
        return orderRepository.findByOrderNo(orderNo)
            .orElseThrow(() -> new RuntimeException("Order not found"));
    }

    @Transactional
    public Order create(Order order) {
        // If user is authenticated, attach the buyer (Profile) automatically
        // so frontend doesn't need to provide buyer info when logged in.
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication != null && authentication.isAuthenticated() &&
            !"anonymousUser".equals(authentication.getPrincipal())) {
            String email = authentication.getName();
            try {
                Profile buyer = profileService.findByEmail(email);
                order.setBuyer(buyer);
            } catch (RuntimeException ex) {
                // If profile not found, proceed without buyer (should be unusual)
            }
        }
        // Force INSERT and immediately refresh the managed entity so that
        // values generated by DB triggers/defaults (like orderNo) are populated
        // into the returned object. Using refresh avoids returning a cached
        // instance without the DB-generated values.
        Order saved = orderRepository.saveAndFlush(order);
        entityManager.refresh(saved);
        return saved;
    }

    public Order update(Long id, Order order) {
        Order existing = findById(id);
        // Chỉ cho phép cập nhật trạng thái và ghi chú
        existing.setStatus(order.getStatus());
        if (order.getNotes() != null) {
            existing.setNotes(order.getNotes());
        }
        return orderRepository.save(existing);
    }

    public List<Order> findMyOrders() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication == null || !authentication.isAuthenticated()) {
            throw new RuntimeException("User not authenticated");
        }
        
        String email = authentication.getName(); // email of the user
        Profile buyer = profileService.findByEmail(email);
        return orderRepository.findByBuyer(buyer);
    }
}
