package com.example.bvtv_www.entity;

import com.example.bvtv_www.enums.DocumentStatus;
import com.example.bvtv_www.enums.PaymentStatus;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.*;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Phiếu Nhập Hàng (PNH)
 * Ghi nhận việc nhập hàng từ nhà cung cấp vào kho
 */
@Data
@Entity
@Table(name = "goods_receipts")
public class GoodsReceipt {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "receipt_no", unique = true, insertable = false, updatable = false, length = 30)
    private String receiptNo;  // PNH-YYYYMMDD-XXXX (auto-generated by trigger)

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "supplier_id")
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private Profile supplier;  // Nhà cung cấp

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "warehouse_id", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private Warehouse warehouse;  // Kho nhập

    @Column(name = "total_amount", nullable = false)
    private BigDecimal totalAmount = BigDecimal.ZERO;  // Tổng tiền hàng (chưa bao gồm VAT)

    @Column(name = "total_vat", nullable = false)
    private BigDecimal totalVat = BigDecimal.ZERO;  // Tổng tiền VAT

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_status", nullable = false, length = 20)
    private PaymentStatus paymentStatus = PaymentStatus.UNPAID;

    @Column(columnDefinition = "TEXT")
    private String notes;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private DocumentStatus status = DocumentStatus.DRAFT;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "created_by")
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private Profile createdBy;  // Người tạo phiếu

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    @OneToMany(mappedBy = "receipt", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonManagedReference
    private List<GoodsReceiptItem> items = new ArrayList<>();

    // Helper methods
    public void addItem(GoodsReceiptItem item) {
        items.add(item);
        item.setReceipt(this);
    }

    public void removeItem(GoodsReceiptItem item) {
        items.remove(item);
        item.setReceipt(null);
    }

    /**
     * Tính tổng tiền từ các items (bao gồm cả VAT)
     */
    public void calculateTotalAmount() {
        // Tính tổng tiền hàng
        this.totalAmount = items.stream()
                .map(item -> item.getUnitCost().multiply(BigDecimal.valueOf(item.getQuantity())))
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        
        // Tính tổng VAT dựa trên vat_rate của product_unit
        this.totalVat = items.stream()
                .map(item -> {
                    BigDecimal lineTotal = item.getUnitCost().multiply(BigDecimal.valueOf(item.getQuantity()));
                    BigDecimal vatRate = item.getProductUnit().getVatRate();
                    return lineTotal.multiply(vatRate).divide(BigDecimal.valueOf(100));
                })
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }
    
    /**
     * Tính tổng tiền phải trả (totalAmount + totalVat)
     */
    public BigDecimal getGrandTotal() {
        return totalAmount.add(totalVat);
    }
}
